/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131314',
        surface: '#131314',
        'surface-dim': '#131314',
        'surface-bright': '#39393a',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-low': '#1b1b1d',
        'surface-container': '#201f21',
        'surface-container-high': '#2a2a2b',
        'surface-container-highest': '#353436',
        'surface-variant': '#353436',
        'on-surface': '#e5e2e3',
        'on-surface-variant': '#c6c6cc',
        'inverse-surface': '#e5e2e3',
        'inverse-on-surface': '#313031',
        outline: '#909096',
        'outline-variant': '#45464c',
        'surface-tint': '#c1c6d9',
        primary: '#c1c6d9',
        'on-primary': '#2a303f',
        'primary-container': '#121826',
        'on-primary-container': '#7b8193',
        'inverse-primary': '#585e6f',
        'primary-fixed': '#dde2f6',
        'primary-fixed-dim': '#c1c6d9',
        'on-primary-fixed': '#151b29',
        'on-primary-fixed-variant': '#414756',
        secondary: '#c1c7cf',
        'on-secondary': '#2b3137',
        'secondary-container': '#41474e',
        'on-secondary-container': '#afb6bd',
        'secondary-fixed': '#dde3eb',
        'secondary-fixed-dim': '#c1c7cf',
        'on-secondary-fixed': '#161c22',
        'on-secondary-fixed-variant': '#41474e',
        tertiary: '#c4c0fc',
        'on-tertiary': '#2d2a5c',
        'tertiary-container': '#141042',
        'on-tertiary-container': '#7e7cb2',
        'tertiary-fixed': '#e3dfff',
        'tertiary-fixed-dim': '#c4c0fc',
        'on-tertiary-fixed': '#171446',
        'on-tertiary-fixed-variant': '#434174',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'on-background': '#e5e2e3',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      backdropBlur: {
        glass: '16px',
      },
      animation: {
        'pulse-glow': 'pulseGlow 8s ease-in-out infinite',
        'breath-in': 'breathIn 4s ease-in-out forwards',
        'breath-out': 'breathOut 4s ease-in-out forwards',
        'fade-in': 'fadeIn 0.5s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
      },
      keyframes: {
        pulseGlow: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.6' },
          '50%': { transform: 'scale(1.05)', opacity: '1' },
        },
        breathIn: {
          '0%': { transform: 'scale(1)', boxShadow: '0 0 40px 5px rgba(196,192,252,0.1)' },
          '100%': { transform: 'scale(1.25)', boxShadow: '0 0 80px 20px rgba(196,192,252,0.3)' },
        },
        breathOut: {
          '0%': { transform: 'scale(1.25)', boxShadow: '0 0 80px 20px rgba(196,192,252,0.3)' },
          '100%': { transform: 'scale(1)', boxShadow: '0 0 40px 5px rgba(196,192,252,0.1)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
